//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtlBaiGiang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LectureReview
    {
        public int ReviewID { get; set; }
        public int LectureID { get; set; }
        public int UserID { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Lecture Lecture { get; set; }
        public virtual User User { get; set; }
    }
}
